# Generated by Django 3.0 on 2020-05-25 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RipperApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
